version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      actions:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      dev-dependencies:
        dependency-type: "development"
        update-types:
        - "patch"
        - "minor"
      prod-dependencies:
        dependency-type: "production"
        update-types:
        - "patch"
        - "minor"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
